version: "3.7"
services:
  # Backend Services
  rabbit:
    image: rabbitmq
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
    volumes:
      - ./configuration/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./configuration/enabled_plugins:/etc/rabbitmq/enabled_plugins
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - /data/redis:/data
    secrets:
      - redis.conf
    command: redis-server /run/secrets/redis.conf
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  # Primitive Services
  parser:
    image: nuthan-db.se.rit.edu/samaritan-parser
    depends_on:
      - "rabbit"
    environment:
      LD_LIBRARY_PATH: "/usr/local/lib"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  project:
    image: nuthan-db.se.rit.edu/samaritan-project
    depends_on:
      - "rabbit"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  repository:
    image: nuthan-db.se.rit.edu/samaritan-repository
    volumes:
      - ${REPOSITORIES_ROOT}:/samaritan/repositories
      - ${CACHE_ROOT}:/samaritan/cache
    depends_on:
      - "rabbit"
      - "project"
    environment:
      REPOSITORIES_ROOT: "/samaritan/repositories"
      CACHE_ROOT: "/samaritan/cache"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
  understand:
    image: nuthan-db.se.rit.edu/samaritan-understand
    volumes:
      - ${REPOSITORIES_ROOT}:/samaritan/repositories
      - ${UNDERSTAND_ROOT}:/samaritan/understand
    depends_on:
      - "rabbit"
      - "project"
    environment:
      UNDERSTAND_ROOT: "/samaritan/understand"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  # Metric Services
  churn:
    image: nuthan-db.se.rit.edu/samaritan-metrics-churn
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  collaboration:
    image: nuthan-db.se.rit.edu/samaritan-metrics-collaboration
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  contribution:
    image: nuthan-db.se.rit.edu/samaritan-metrics-contribution
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  complexity:
    image: nuthan-db.se.rit.edu/samaritan-metrics-complexity
    depends_on:
      - "project"
      - "rabbit"
      - "understand"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  flow:
    image: nuthan-db.se.rit.edu/samaritan-metrics-flow
    depends_on:
      - "project"
      - "rabbit"
      - "understand"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  functionchurn:
    image: nuthan-db.se.rit.edu/samaritan-metrics-functionchurn
    depends_on:
      - "project"
      - "rabbit"
      - "repository"
      - "redis"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  hunk:
    image: nuthan-db.se.rit.edu/samaritan-metrics-hunk
    depends_on:
      - "project"
      - "rabbit"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  keyword:
    image: nuthan-db.se.rit.edu/samaritan-metrics-keyword
    depends_on:
      - "project"
      - "rabbit"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  loc:
    image: nuthan-db.se.rit.edu/samaritan-metrics-loc
    depends_on:
      - "rabbit"
      - "repository"
      - "understand"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  messagetokens:
    image: nuthan-db.se.rit.edu/samaritan-metrics-messagetokens
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  nesting:
    image: nuthan-db.se.rit.edu/samaritan-metrics-nesting
    depends_on:
      - "project"
      - "rabbit"
      - "understand"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  offender:
    image: nuthan-db.se.rit.edu/samaritan-metrics-offender
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  ownership:
    image: nuthan-db.se.rit.edu/samaritan-metrics-ownership
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  pastauthors:
    image: nuthan-db.se.rit.edu/samaritan-metrics-pastauthors
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  pastchanges:
    image: nuthan-db.se.rit.edu/samaritan-metrics-pastchanges
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  patchtokens:
    image: nuthan-db.se.rit.edu/samaritan-metrics-patchtokens
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
secrets:
  redis.conf:
    external: true
