version: "3.7"
services:
  rabbit:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  redis:
    image: redis
    command: [
      "bash", "-c",
      '
        docker-entrypoint.sh
        --requirepass password
        --appendonly yes
      '
    ]
    volumes:
      - redis:/data
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  project:
    image: nuthan-db.se.rit.edu/samaritan-project
    depends_on:
      - "rabbit"
    links:
      - "rabbit:samaritan-rabbit"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  repository:
    image: nuthan-db.se.rit.edu/samaritan-repository
    volumes:
      - repositories:/samaritan/repositories
    depends_on:
      - "rabbit"
      - "redis"
      - "project"
    links:
      - "rabbit:samaritan-rabbit"
      - "redis:samaritan-redis"
      - "project:samaritan-project"
    environment:
      REPOSITORIES_ROOT: "/samaritan/repositories"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_INDEX: "11"
      REDIS_PASSWORD: "password"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
  understand:
    image: nuthan-db.se.rit.edu/samaritan-understand
    volumes:
      - repositories:/samaritan/repositories
      - understand:/samaritan/understand
    depends_on:
      - "rabbit"
      - "project"
    links:
      - "rabbit:samaritan-rabbit"
      - "project:samaritan-project"
    environment:
      UNDERSTAND_ROOT: "/samaritan/understand"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  loc:
    image: nuthan-db.se.rit.edu/samaritan-metrics-loc
    volumes:
      - repositories:/samaritan/repositories
    depends_on:
      - "rabbit"
      - "repository"
    links:
      - "rabbit:samaritan-rabbit"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  churn:
    image: nuthan-db.se.rit.edu/samaritan-metrics-churn
    depends_on:
      - "rabbit"
      - "repository"
    links:
      - "rabbit:samaritan-rabbit"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  collaboration:
    image: nuthan-db.se.rit.edu/samaritan-metrics-collaboration
    depends_on:
      - "rabbit"
      - "repository"
    links:
      - "rabbit:samaritan-rabbit"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  contribution:
    image: nuthan-db.se.rit.edu/samaritan-metrics-contribution
    depends_on:
      - "rabbit"
      - "repository"
    links:
      - "rabbit:samaritan-rabbit"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  offender:
    image: nuthan-db.se.rit.edu/samaritan-metrics-offender
    depends_on:
      - "rabbit"
      - "repository"
    links:
      - "rabbit:samaritan-rabbit"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  complexity:
    image: nuthan-db.se.rit.edu/samaritan-metrics-complexity
    depends_on:
      - "project"
      - "rabbit"
      - "understand"
    links:
      - "rabbit:samaritan-rabbit"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  flow:
    image: nuthan-db.se.rit.edu/samaritan-metrics-flow
    depends_on:
      - "project"
      - "rabbit"
      - "understand"
    links:
      - "rabbit:samaritan-rabbit"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  nesting:
    image: nuthan-db.se.rit.edu/samaritan-metrics-nesting
    depends_on:
      - "project"
      - "rabbit"
      - "understand"
    links:
      - "rabbit:samaritan-rabbit"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_HEARTBEAT: 600
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
volumes:
  repositories:
    external: true
  redis:
    external: true
  understand:
    external: true
