version: "3.7"
services:
  # Backend Services
  rabbit:
    image: rabbitmq:3.7
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
    volumes:
      - ./configuration/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./configuration/enabled_plugins:/etc/rabbitmq/enabled_plugins
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - /data/redis:/data
    secrets:
      - redis.conf
    command: redis-server /run/secrets/redis.conf
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  # Primitive Services
  parser:
    image: docker.pkg.github.com/samaritan/services/samaritan-parser:0.3.1-alpha
    depends_on:
      - "rabbit"
    environment:
      LD_LIBRARY_PATH: "/usr/local/lib"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  project:
    image: docker.pkg.github.com/samaritan/services/samaritan-project:0.2.0-alpha
    depends_on:
      - "rabbit"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  repository:
    image: docker.pkg.github.com/samaritan/services/samaritan-repository:0.2.0-alpha
    volumes:
      - ${REPOSITORIES_ROOT}:/samaritan/repositories
      - ${CACHE_ROOT}:/samaritan/cache
    depends_on:
      - "rabbit"
      - "project"
    environment:
      REPOSITORIES_ROOT: "/samaritan/repositories"
      CACHE_ROOT: "/samaritan/cache"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  understand:
    image: docker.pkg.github.com/samaritan/services/samaritan-understand:0.1.0-alpha
    volumes:
      - ${REPOSITORIES_ROOT}:/samaritan/repositories
      - ${UNDERSTAND_ROOT}:/samaritan/understand
    depends_on:
      - "rabbit"
      - "project"
    environment:
      UNDERSTAND_ROOT: "/samaritan/understand"
      UNDERSTAND_LICENSE: "${UNDERSTAND_LICENSE}"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  # Metric Services
  churn:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-churn:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  collaboration:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-collaboration:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  contribution:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-contribution:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  complexity:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-complexity:0.2.0-alpha
    depends_on:
      - "project"
      - "rabbit"
      - "understand"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  flow:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-flow:0.2.0-alpha
    depends_on:
      - "project"
      - "rabbit"
      - "understand"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  functionchurn:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-functionchurn:0.2.0-alpha
    depends_on:
      - "project"
      - "rabbit"
      - "repository"
      - "redis"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  hunk:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-hunk:0.2.0-alpha
    depends_on:
      - "project"
      - "rabbit"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  interactivechurn:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-interactivechurn:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  keyword:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-keyword:0.2.0-alpha
    depends_on:
      - "project"
      - "rabbit"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  loc:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-loc:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
      - "understand"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  messagetokens:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-messagetokens:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  nesting:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-nesting:0.2.0-alpha
    depends_on:
      - "project"
      - "rabbit"
      - "understand"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  offender:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-offender:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  ownership:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-ownership:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  pastauthors:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-pastauthors:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  pastchanges:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-pastchanges:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  patchtokens:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-patchtokens:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  relativechurn:
    image: docker.pkg.github.com/samaritan/services/samaritan-metrics-relativechurn:0.2.0-alpha
    depends_on:
      - "rabbit"
      - "repository"
      - "churn"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_HEARTBEAT: ${RABBIT_HEARTBEAT}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
secrets:
  redis.conf:
    external: true
