AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/
HEARTBEAT: ${RABBIT_HEARTBEAT:60}
REPOSITORIES_ROOT: ${REPOSITORIES_ROOT:'/dev/shm'}
CODEDX_URL: ${CODEDX_URL:http://localhost:8080/}
CODEDX_INTERVAL: ${CODEDX_INTERVAL:15}
CODEDX_KEY: ${CODEDX_KEY}
LOGGING:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(process)d:%(thread)d - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
  loggers:
    analyzer:
      level: DEBUG
      handlers: [console]
      propagate: false
  root:
    level: ERROR
    handlers: [console]
