AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/
HEARTBEAT: ${RABBIT_HEARTBEAT:60}
REPOSITORIES_ROOT: ${REPOSITORIES_ROOT:'/dev/shm'}
CACHE_ROOT: ${CACHE_ROOT:'/dev/shm'}
REDIS_URL: redis://:${REDIS_PASSWORD:guest}@${REDIS_HOST:localhost}/0
LOGGING:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(process)d:%(thread)d - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
  loggers:
    repository:
      level: DEBUG
      handlers: [console]
      propagate: false
  root:
    level: ERROR
    handlers: [console]
