AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/?heartbeat=${RABBIT_HEARTBEAT:60}
REDIS_URI: redis://user:${REDIS_PASSWORD:password}@${REDIS_HOST:localhost}:${REDIS_PORT:6379}/${REDIS_INDEX:11}
REPOSITORIES_ROOT: ${REPOSITORIES_ROOT:'/dev/shm'}
LOGGING:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(process)d:%(thread)d - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
  loggers:
    repository:
      level: DEBUG
      handlers: [console]
      propagate: false
  root:
    level: ERROR
    handlers: [console]
